export const INPUT_TICKETS = 'INPUT_TICKETS';
export const ACCEPTED_TICKETS = 'ACCEPTED_TICKETS';
export const RESOLVED_TICKETS = 'RESOLVED_TICKETS';
export const CONFIRMED_TICKETS = 'CONFIRMED_TICKETS';
export const LAST_ID = 'LAST_ID';

const properties = {
    TICKETS: 'TICKETS',
    INPUT_TICKETS,
    ACCEPTED_TICKETS,
    RESOLVED_TICKETS,
    CONFIRMED_TICKETS,
    LAST_ID
}

export default properties;